sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t bhmkyndryl/multiapp-docker-testbuild -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bhmkyndryl/multiapp-docker-testbuild npm run test


after_success:
  - docker build -t bhmkyndryl/multiapp-client ./client
  - docker build -t bhmkyndryl/multiapp-nginx ./nginx
  - docker build -t bhmkyndryl/multiapp-server ./server
  - docker build -t bhmkyndryl/multiapp-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push bhmkyndryl/multiapp-client
  - docker push bhmkyndryl/multiapp-nginx
  - docker push bhmkyndryl/multiapp-server
  - docker push bhmkyndryl/multiapp-worker

# Hum, wake up please !
deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "multiapp"
  env: "Multiapp-env"
  bucket_name: "elasticbeanstalk-eu-west-3-015806071036"
  bucket_path: "multiapp-bucket"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
   