sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t bhm-kyndryl/multiapp-docker-testbuild -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bhm-kyndryl/docker-react npm run test


after_success:
  - docker build -t bhm-kyndryl/multiapp-client ./client
  - docker build -t bhm-kyndryl/multiapp-nginx ./nginx
  - docker build -t bhm-kyndryl/multiapp-server ./server
  - docker build -t bhm-kyndryl/multiapp-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push bhm-kyndryl/multiapp-client
  - docker push bhm-kyndryl/multiapp-nginx
  - docker push bhm-kyndryl/multiapp-server
  - docker push bhm-kyndryl/multiapp-worker



# deploy:
  # provider: elasticbeanstalk
  # region: "eu-west-3"
  # app: "docker-react"
  # env: "Dockerreact-env"
  # bucket_name: "elasticbeanstalk-eu-west-3-015806071036"
  # bucket_path: "docker-react"
  # on:
    # branch: main
  # access_key_id: $AWS_ACCESS_KEY
  # secret_access_key: $AWS_SECRET_KEY
   